
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true      # h2-console 접근 허용
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop   # 개발용: 시작 시 생성, 종료 시 삭제
    show-sql: true            # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true      # SQL 보기 좋게 포맷
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace  # 파라미터 바인딩 확인